name: CI

on: [push]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@master
    - name: Print
      run: echo Teraform Commands..
    - name: 'Checkout'
      uses: actions/checkout@master
    - name: 'Terraform Format'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'fmt'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
